# ------------------------------Install Libraries------------------------------
# install.packages("plyr")
# install.packages("dplyr")
# install.packages("stringr")
# install.packages("randomForest")
# install.packages("caret")
# install.packages("e1071")
# install.packages("ROSE")
# install.packages("ggplot2")
# install.packages(c("tm", "SnowballC", "wordcloud", "RColorBrewer", "RCurl", "XML"))


# ------------------------------Load Libraries------------------------------
library(plyr)
library(dplyr)
library(stringr)
library(randomForest)
library(caret)
library(ROSE)
library(shiny)
library(shinyalert)
library(ggplot2)
library(tm)
library(SnowballC)
library(wordcloud)
library(RCurl)
library(XML)
library(RColorBrewer)