source(file.path(getwd(), "load_libraries.R"))

generatePlots <- function(output) {

  rf_model <- readRDS(file.path(getwd(), "rf_model.rds"))

  data <- read.csv("../../Data/diabetes_data_new.csv")
  data <- data[, - c(1)] # Removing annonymous column generated by write.csv() for mapping observations

  for (col in colnames(data)) {
    if (is.numeric(data[, col]) & col != "readmitted") {
      data[, col] <- as.numeric(data[, col])
    } else {
      data[, col] <- as.factor(data[, col])
    }
  }
  variable_importance_plot <- ggplot(varImp(rf_model), aes(x = rownames(varImp(rf_model)), y = Overall)) + labs(title = "Variable Importance Chart\n", x = "Important_Variables", y = "Importance")
  output$variable_importance_plot <- renderPlot(variable_importance_plot + geom_bar(stat = "identity", fill = "#34626c", width = 0.5) + coord_flip() + theme_light())

  output$num_procedures_plot <- renderPlot(ggplot(data, aes(x = num_procedures, group = readmitted, fill = readmitted)) +
  geom_histogram(position = "identity", alpha = 0.8, binwidth = 1) + theme_bw())

  output$time_in_hopital_plot <- renderPlot(ggplot(data, aes(x = time_in_hospital, group = readmitted, fill = readmitted)) +
  geom_histogram(position = "identity", alpha = 0.8, binwidth = 1) + theme_bw())

  output$number_diagnoses_plot <- renderPlot(ggplot(data, aes(number_diagnoses, group = readmitted, fill = readmitted)) +
  geom_histogram(position = "identity", alpha = 0.8, binwidth = 1) + theme_bw())

  output$num_lab_procedures_plot <- renderPlot(ggplot(data, aes(num_lab_procedures, group = readmitted, fill = readmitted)) +
  geom_histogram(position = "identity", alpha = 0.8, binwidth = 1) + theme_bw())

  output$num_medications_plot <- renderPlot(ggplot(data, aes(num_medications, group = readmitted, fill = readmitted)) +
  geom_histogram(position = "identity", alpha = 0.8, binwidth = 1) + theme_bw())


  return(output)
}

saveRDS(generatePlots, file = "../App/DiabetesPrediction/generatePlots.rds")

# wordcloud(words = paste(scan(file.path(getwd(), "cloud.txt"), what = "character", sep = " "), collapse = " "), min.freq = 2,
#           max.words = 10000, random.order = TRUE, rot.per = 0.35, colors = brewer.pal(8, "Dark2"))
