source("RScript/load_libraries.R")

# ------------------------------Reading Prepared Data------------------------------
data <- read.csv("Data/diabetes_data_new.csv")
data <- data[, - c(1)] # Removing annonymous column generated by write.csv() for mapping observations

for (col in 1:ncol(data)) {
  if (is.numeric(data[, col])) {
    data[, col] <- as.numeric(data[, col])
  } else {
    data[, col] <- as.factor(data[, col])
  }
}



# ------------------------------Dividing Data for Training & Testing------------------------------
# Split the Dataset into Training Data and Test Data.
# Use set.seed(100) as a seed and split the dataset into training and test set with 80:20 proportion, respectively.
set.seed(123)
id <- sample(2, nrow(data), replace = T, prob = c(0.8, 0.2))
data_train <- data[id == 1,]
data_test <- data[id == 2,]



# ------------------------------Data Balancing------------------------------
data_train <- ROSE(readmitted ~ ., data = data_train)$data




# ------------------------------Training Model------------------------------
data_train$readmitted <- as.factor(data_train$readmitted)
data_test$readmitted <- as.factor(data_test$readmitted)

# rf_model <- randomForest(readmitted ~ time_in_hospital +
# num_procedures + number_diagnoses + num_lab_procedures +
# num_medications + primary_diagnosis + secondary_diagnosis +
# tertiary_diagnosis + age + insulin + race + gender,
# data = data_train, mtry = 12, ntree = 400) #<------Can be Configured for more accuracy

# #Saving the model
# saveRDS(rf_model, file = "App/DiabetesPrediction/rf_model.rds")
saveRDS(data_train, file = "App/DiabetesPrediction/data_train.rds")


# ------------------------------
# plot(rf_model) # Error rate of Random Forest and ntree also.
# varImpPlot(rf_model)
# # importance(rf_model)
# varUsed(rf_model)

# prd1 <- predict(rf_model, data_train) # Accuracy = 100%
# prd2 <- predict(rf_model, data_test) # Accuracy = 74%

# confusionMatrix(prd1, data_train$readmitted)
# confusionMatrix(prd2, data_test$readmitted)
# ------------------------------
# # Calculate mtry for the random forest model
# t <- tuneRF(data_train[, -41], data_train[, 41],
#             stepFactor = 0.5,
#             plot = TRUE,
#             ntreeTry = 400,
#             trace = TRUE,
#             improve = 0.05
#             )
# ------------------------------
