rf_model <- readRDS(file.path(getwd(), "Assets/rf_model.rds"))
# rf_model42 <- readRDS(file.path(getwd(), "Assets/rf_model42.rds"))

data <- read.csv("Assets/diabetes_data_new.csv")
data <- data[, - c(1)] # Removing annonymous column generated by write.csv() for mapping observations
attach(data)



for (col in colnames(data)) {
  if (is.numeric(data[, col]) & col != "readmitted") {
    data[, col] <- as.numeric(data[, col])
  } else {
    data[, col] <- as.factor(data[, col])
  }
}


generatePlots <- function(output) {


  #--------------------Instructions---------------------

  # For new plot, follow this syntax --->
  # output$[PLOT_NAME] <- renderPlot(...plot function as usual)

  # ----------------------------------------------------



  #--------------------Patient Statistics---------------
  # ----------------------------------------------------
  patients_race_plot <- reactive({
    function() {
      data_race <- data.frame(table(race))
      ggplot(data_race, aes(x = race, y = Freq)) +
      labs(title = "Patients over Race\n", x = "Races", y = "Patient_Count") +
      geom_bar(stat = "identity", fill = "#eda361", width = 0.5) +
      theme_minimal() + geom_text(aes(label = Freq)) +
      theme(plot.title = element_text(size = 25, face="bold"))
    }
  })
  output$patients_race_plot1 <- renderPlot({ patients_race_plot()() })
  output$patients_race_plot2 <- renderPlot({ patients_race_plot()() })
  # ----------------------------------------------------




  # ----------------------------------------------------
  patient_gender_plot <- reactive({
    function() {
      # data_gender <- data.frame(table(gender))
      # mycols <- c("#c7f582", "#8eebf5")
      # label_y <- cumsum(data_gender$Freq) - 0.5 * data_gender$Freq
      # ggplot(data_gender, aes(x = "", y = Freq, fill = gender)) +
      # geom_bar(width = 1, stat = "identity", color = "white") +
      # coord_polar("y", start = 0) +
      # geom_text(aes(y = label_y, label = Freq), color = "black", size = 3) +
      # scale_fill_manual(values = mycols) +
      # labs(title = "Patients over Gender") +
      # theme_void()
      data_gender <- data.frame(table(gender))
      piepercent<- round(100*data_gender$Freq/sum(data_gender$Freq), 1)
      lbls <- paste(piepercent,"%",sep="")
      pie(data_gender$Freq, labels = lbls, main = "Patients over Gender",cex.main=2, radius = 1,col = c("#c7f582", "#8eebf5"))
      legend(1.2, .1, c("Female", "Male"), cex = 0.8,fill =  c("#c7f582", "#8eebf5"))
    }
  })
  output$patient_gender_plot1 <- renderPlot({ patient_gender_plot()() })
  output$patient_gender_plot2 <- renderPlot({ patient_gender_plot()() })
  # ----------------------------------------------------




  # ----------------------------------------------------
  patient_age_plot <- reactive({
    function() {
      data_age <- data.frame(table(age))
      ggplot(data_age, aes(x = age, y = Freq)) + geom_point(size = 3) +
      geom_segment(aes(x = age, xend = age, y = 0, yend = Freq)) +
      geom_text(aes(label = Freq), size = 3, position = position_dodge(width = 0.9), vjust = -0.9) +
      labs(title = "Patients over Age\n", x = "Age_Groups", y = "Patient_Count") + theme_light() +
      coord_cartesian(ylim = c(0, 15100)) +
      theme(plot.title = element_text(size = 25, face="bold"))
    }
  })
  output$patient_age_plot1 <- renderPlot({ patient_age_plot()() })
  output$patient_age_plot2 <- renderPlot({ patient_age_plot()() })

  # ----------------------------------------------------




  # ----------------------------------------------------
  patient_AdmType_plot <- reactive({
    function() {
      data_admtype <- data.frame(table(admission_type))
      ggplot(data_admtype, aes(x = admission_type, y = Freq)) +
      labs(title = "Patients over Admission Type\n", x = "Admission Type", y = "Patient_Count") +
      geom_bar(stat = "identity", fill = "#96cce3", width = 0.5) +
      geom_text(aes(label = Freq)) + theme_light() + coord_flip() +
      theme(plot.title = element_text(size = 25, face="bold"))
    }
  })
  output$patient_AdmType_plot1 <- renderPlot({ patient_AdmType_plot()() })
  output$patient_AdmType_plot2 <- renderPlot({ patient_AdmType_plot()() })

  # ----------------------------------------------------




  #--------------------Re-admission Distribution--------
  # ----------------------------------------------------
  num_procedures_plot <- reactive({
    function() {
      mycols <- c("#b3f5de", "#fc0000")
      data_ <- data.frame(table(num_procedures, readmitted))
      ggplot(data_, aes(x = num_procedures, y = Freq, fill = factor(readmitted))) +
      geom_bar(stat = 'identity', position = 'dodge') +
      labs(title = "Readmission over Num of Procedures\n", x = 'Number of Procedures', y = 'Patient Count', fill = "Readmitted(<30)") +
      scale_fill_manual(values = mycols) + theme_light() +
      geom_text(aes(label = Freq), position = position_dodge(width = 0.9), vjust = -0.25, size = 3) +
      theme(plot.title = element_text(size = 25, face="bold"))
    }
  })
  output$num_procedures_plot1 <- renderPlot({ num_procedures_plot()() })
  output$num_procedures_plot2 <- renderPlot({ num_procedures_plot()() })

  # ----------------------------------------------------




  # ----------------------------------------------------
  time_in_hospital_plot <- reactive({
    function() {
      mycols <- c("#b3f5de", "#fc0000")
      data_ <- data.frame(table(time_in_hospital, readmitted))

      ggplot(data_, aes(x = time_in_hospital, y = Freq, fill = factor(readmitted))) +
      geom_bar(stat = 'identity', position = 'dodge') +
      labs(title = "Readmission over Time in Hospital\n", x = 'Time in Hospital (in Days)', y = 'Patient Count', fill = "Readmitted(<30)") +
      scale_fill_manual(values = mycols) + theme_bw() +
      geom_text(aes(label = Freq), position = position_dodge(width = 0.9), vjust = -0.25, size = 3) +
      theme(plot.title = element_text(size = 25, face="bold"))
    }
  })
  output$time_in_hospital_plot1 <- renderPlot({ time_in_hospital_plot()() })
  output$time_in_hospital_plot2 <- renderPlot({ time_in_hospital_plot()() })

  # ----------------------------------------------------




  # ----------------------------------------------------
  number_diagnoses_plot <- reactive({
    function() {
      mycols <- c("#b3f5de", "#fc0000")
      data_ <- data.frame(table(number_diagnoses, readmitted))
      ggplot(data_, aes(x = number_diagnoses, y = Freq, fill = factor(readmitted))) +
      geom_bar(stat = 'identity', position = 'dodge') +
      labs(title = "Readmission over Num of Diagnosis\n", x = 'Number of Diagnosis', y = 'Patient Count', fill = "Readmitted(<30)") +
      scale_fill_manual(values = mycols) + theme_bw() +
      geom_text(aes(label = Freq), position = position_dodge(width = 0.9), vjust = -0.25, size = 3) +
      theme(plot.title = element_text(size = 25, face="bold"))
    }
  })
  output$number_diagnoses_plot1 <- renderPlot({ number_diagnoses_plot()() })
  output$number_diagnoses_plot2 <- renderPlot({ number_diagnoses_plot()() })
  # ----------------------------------------------------




  # ----------------------------------------------------
  num_medications_plot <- reactive({
    function() {
      mycols <- c("#b3f5de", "#fc0000")
      data_ <- data.frame(table(num_medications, readmitted))
      ggplot(data_, aes(x = num_medications, y = Freq, fill = factor(readmitted))) +
      geom_bar(stat = 'identity', position = 'dodge', width = 0.5) +
      labs(title = "Readmission over Num of Medications\n", x = 'Number of Medications', y = 'Patient Count', fill = "Readmitted(<30)") +
      scale_fill_manual(values = mycols) + theme_bw() +
      geom_text(aes(label = Freq), position = position_dodge(width = 0.9), hjust = -0.4, size = 2.5, angle = 90) +
      coord_cartesian(ylim = c(0, 3700)) +
      theme(plot.title = element_text(size = 25, face="bold"))
    }
  })
  output$num_medications_plot1 <- renderPlot({ num_medications_plot()() })
  output$num_medications_plot2 <- renderPlot({ num_medications_plot()() })
  # ----------------------------------------------------




  # ----------------------------------------------------
  num_lab_procedures_plot <- reactive({
    function() {
      mycols <- c("#b3f5de", "#fc0000")
      ggplot(data, aes(x = num_lab_procedures, fill = factor(readmitted))) +
      geom_bar(stat = 'count', position = 'dodge', width = 0.5) +
      labs(title = "Readmission over Num of Lab Procedures\n", x = 'Number of Lab Procedures', y = 'Patient Count', fill = "Readmitted(<30)") +
      scale_fill_manual(values = mycols) + theme_bw() +
      theme(plot.title = element_text(size = 25, face="bold"))
    }
  })
  output$num_lab_procedures_plot1 <- renderPlot({ num_lab_procedures_plot()() })
  output$num_lab_procedures_plot2 <- renderPlot({ num_lab_procedures_plot()() })
  # ----------------------------------------------------




  # --------------------Data Analysis-------------------
  # ----------------------------------------------------
  corr_heatmap <- reactive({
    function() {
      data_cor1 <- data.frame(data[, c("time_in_hospital", "num_procedures", "number_diagnoses", "num_lab_procedures", "num_medications")])
      corr <- round(cor(data_cor1), 1)
      ggcorrplot(corr, hc.order = TRUE, type = "lower",
           lab = TRUE, ggtheme = ggplot2::theme_gray,
           colors = c("#6D9EC1", "white", "#E46726"),
           title = "Correlation HeatMap\n",
           outline.color = "blue") +
      theme(plot.title = element_text(size = 20, face="bold"))
    }
  })
  output$corr_heatmap1 <- renderPlot({ corr_heatmap()() })
  output$corr_heatmap2 <- renderPlot({ corr_heatmap()() })
  # ----------------------------------------------------




  # ----------------------------------------------------
  corr_matrix <- reactive({
    function() {
      #     data_cor1 <- data.frame(data[, c("time_in_hospital", "num_procedures", "number_diagnoses", "num_lab_procedures", "num_medications")])
      #     #png(file = "city.jpg")
      #     ggpairs(data_cor1, title="correlogram with ggpairs()")
      #     #dev.off()
      pfad <- file.path(getwd(), "Assets/corr_matrix.jpg")
      list(src = pfad,
          contentType = "image/jpg",
          width = "100%",
          height = 400,
          alt = "Correlation Matrix")
    }
  })
  output$corr_matrix1 <- renderImage({ corr_matrix()() })
  output$corr_matrix2 <- renderImage({ corr_matrix()() })
  # ----------------------------------------------------




  # ----------------------------------------------------
  # wordcloud <- reactive({
  #   function() {
  #     pfad <- ""
  #     list(src = pfad,
  #        contentType = "image/jpg",
  #        width = 400,
  #        height = 300,
  #        alt = "Wordcloud")
  #   }, deleteFile = F)
  # })
  # ----------------------------------------------------




  # --------------------Modeling Summaries--------------
  # ----------------------------------------------------
  variable_importance <- reactive({
    function() {
      # importance <- importance(rf_model42)
      # varImportance <- data.frame(Variables = row.names(importance), Importance = round(importance[, 'MeanDecreaseGini'], 2))

      # # Create a rank variable based on importance
      # rankImportance <- mutate(varImportance, Rank = paste0('#', dense_rank(desc(Importance))))
      # # Use ggplot2 to visualize the relative importance of variables
      # ggplot(rankImportance, aes(x = reorder(Variables, Importance), y = Importance, fill = Importance)) +
      # geom_bar(stat = 'identity', width = 0.7) +
      # geom_text(aes(x = Variables, y = 0.5, label = Rank), hjust = 1, vjust = 0.25, size = 3, colour = 'red') +
      # labs(x = 'Variables', title = "Relative importance of variables") +
      # coord_flip() + theme_bw()
      pfad <- file.path(getwd(), "Assets/variable_importance_plot.png")
      list(src = pfad,
         contentType = "image/jpg",
          width = "100%",
          height = 700,
         alt = "Variable Importance Plot")
    }
  })
  output$variable_importance1 <- renderImage({ variable_importance()() })
  output$variable_importance2 <- renderImage({ variable_importance()() })
  # ----------------------------------------------------




  # ----------------------------------------------------
  # rf_model42_plot <- reactive({
  #   function() {
  #     pfad <- file.path(getwd(), "Assets/rf_model42_plot.png")
  #     list(src = pfad,
  #        contentType = "image/jpg",
  #        width = "100%",
  #        height = 400,
  #        alt = "Rf_Model _ 42")
  #   }
  # })
  # output$rf_model42_plot1 <- renderImage({ rf_model42_plot()() })
  # output$rf_model42_plot2 <- renderImage({ rf_model42_plot()() })
  # ----------------------------------------------------


  # output$
  # output$

  # output$
  # output$

  # output$
  # output$

  # output$
  # output$

  return(output)
}